### ISSUE TITLE
QA CHECKLIST

### ISSUE THREAD

**Issue by jaydeninniss** [jaydeninniss/JaydenInniss-Portfolio2024#11]
### FULL QA CHECKLIST

**Browsers Support**
 Responsive in ALL viewports
- [ ]  Chrome
- [ ]  Safari
- [ ]  Edge
- [ ]  FireFox
- [ ] MOBILE

**Code & Optimization**

- [ ]  All images under 1MB
- [ ]  Images are in WebP format if applicable
- [ ]  All CSS classes and ID's use the same naming convention
- [ ]  All images have ALT text
- [ ]  All pages under 2.5 MB
- [ ]  No broken links
- [ ]  All complex code functions are properly commented
- [ ]  URLS disclude .PHP or .html
- [ ]  Image galleries are properly linked to the database
- [ ]  URL redirection works - from jaydeninniss.ca -> jaydeninniss.com
- [ ]  "Overflow: hidden"
- [ ]  No errors in console
- [ ]  All videos have same attributes “loop autoplay muted”
- [ ]  All videos have titles and posters
- [ ]  All images under 1MB
- [ ]  All required JS and CSS is included according to the styles hierarchy I wrote out

**Design & UI**

- [ ]  CSS breakpoints added
- [ ]  Colours and design are standardized and following my set variables
- [ ]  Consistent text sizes and weights
- [ ]  All CTAs have a clear destination
- [ ]  Colour Contrast checked
- [ ]  Buttons have hover states
- [ ]  All visible pages are 100% complete.
- [ ]  All animations/interactions are functional

**Content**

- [ ]  No spelling mistakes
- [ ]  Each artifact's deliverables are linked
- [ ]  Images have alt tags
- [ ]  Image galleries are not excessive in length

**SEO**

- [ ] OG tags are specific to each page
- [ ] Metadata is specific to each page
- [ ] Fav Icon works on all of the pages
- [ ] Title and description added
- [ ] Broken pages are not indexed
- [ ] Google Analytics is included in each head
